FROM resin/%%RESIN_MACHINE_NAME%%-python

# Enable systemd
ENV INITSYSTEM on

# copy current directory into /app
COPY . /app

# run python script when container lands on device
CMD ["python", "/app/hello.py"]
